# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: <%= ENV["domain_name"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["facebook_key"] %>
  facebook_secret: <%= ENV["facebook_secret"] %>
  google_storage_key: <%= ENV["google_storage_access_key_id"] %>
  google_storage_secret: <%= ENV["google_storage_secret_access_key"] %>
  fog_directory: <%= ENV["fog_directory"] %>

test:
  secret_key_base: 01ecdaca57b3395579cd97dd99d97ef841b9708db9f8e0bf13de6a25bb1996d8d3979f5d66cc0f4ce649b8798afdc5bdebbedcb010e3e579a26e6944f61cd6c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["domain_name"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["facebook_key"] %>
  facebook_secret: <%= ENV["facebook_secret"] %>
  google_storage_key: <%= ENV["google_storage_access_key_id"] %>
  google_storage_secret: <%= ENV["google_storage_secret_access_key"] %>
  fog_directory: <%= ENV["fog_directory"] %>
